#!/bin/sh
# SDG Gate — pre-commit hook
# Generated by sdg-agents. Pipe through your LLM CLI below.
#
# Default uses 'claude' (Claude Code CLI). Replace with any agent:
#   openai, gemini, ollama, etc.
#
# To skip on a specific commit: git commit --no-verify

set -e

DIFF=$(git diff --staged)

if [ -z "$DIFF" ]; then
  exit 0
fi

RESULT=$(printf '%s' "$DIFF" | sdg-agents gate --prompt | claude --output-format json 2>/dev/null)
LLM_EXIT=$?

if [ $LLM_EXIT -ne 0 ] || [ -z "$RESULT" ]; then
  echo "  ⚠️  SDG Gate: LLM unavailable. Skipping review." >&2
  exit 0
fi

printf '%s' "$RESULT" | sdg-agents gate --check
