#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# NVM Shim (Essential for projects Staff in Linux/NVM)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \\. "$NVM_DIR/nvm.sh"

npm run bump fix